### ISSUE TITLE
Tensorflow version

### ISSUE THREAD

**Issue by xzlyu** [xwhan/DeepPath#16]
Hi, I am trying to run your code to learn some rules, I use python 2.7 and tensorflow 1.12.0 and I have some problems that may be caused by tensorflow's version, so do you still remeber your tensorflow version when you write this code ?
Thanks!

**Comment by ouening** [comment]
python2.7
tensorflow-gpu 1.13.1

**Comment by xzlyu** [comment]
> python2.7
> tensorflow-gpu 1.13.1

Thanks, it surprises me.
