### ISSUE TITLE
Could you explain the program more clearer?

### ISSUE THREAD

**Issue by charlesfufu** [xwhan/DeepPath#17]
![image](https://user-images.githubusercontent.com/33311822/69110947-11ac0300-0ab7-11ea-9d68-2d6df88596b7.png)
I don't know the meaning of these files

**Comment by lzw429** [comment]
I also have some doubts about the input files, e.g., what should the contents of the following two files be?

```
graphpath = dataPath + 'tasks/' + relation + '/' + 'graph.txt'
relationPath = dataPath + 'tasks/' + relation + '/' + 'train_pos'
```

**Comment by xwhan** [comment]
the first file is the graph we are going to find paths; the second file includes the training triples for a particular relation
