### ISSUE TITLE
Training is very slow

### ISSUE THREAD

**Issue by MichaelXin** [xwhan/DeepPath#2]
Hi Wenhan, I try to train this program, but the training is very slow on my machine.
It seems that the program does not use the GPU on my machine.
But I'm sure that the tensorflow in my system can employ the GPU acceleration, because I have tested it using other programs. 
Is there any idea for that? 
Thank you very much!

**Comment by alex10151** [comment]
hi, i  am reading the code recently,but i found a problem  no such file or directory'../NELL-995/tasks/$/train_pos' when i run the file  pathfinder.sh on bash.
do you have any idea about this error ? where are these files? missing or need generating?
thank you for your apply!

**Comment by xwhan** [comment]
Hi Michael, the code will automatically use GPU if you have tensorflow-gpu installed. Maybe you will need to double check that. Also, you may want you may want check whether the code uses your GPU memory during training.
