### ISSUE TITLE
Do you think KG can solve this kind of question?

### ISSUE THREAD

**Issue by guotong1988** [xwhan/DeepPath#3]
1,
A lives in C. `(A, liveInCity, C)`
B lives in C. `(B, liveInCity, C)`
Does A and B live in the same city?

2,
A is 180 cm height. `(A, height, 180)`
B is 175 cm height. `(B, height, 175)`
Is B taller than A?

Thank you very much.

**Comment by guotong1988** [comment]
Thank you.

**Comment by guotong1988** [comment]
How you think Semantic Parsing method for KG? Thank you.

**Comment by xwhan** [comment]
Myself do not work on semantic parsing. You can read Percy Liang or Scott Yih's papers

**Comment by guotong1988** [comment]
Thank you.

**Comment by guotong1988** [comment]
So you think semantic parsing is also promising and hot?

**Comment by xwhan** [comment]
yes
